---
- name: Ensure apache packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    
- name: Start apache
  service:
    name: apache2
    state: started
