---

- name: Setup mysql pass
  debconf:
    name: mysql-server
    question: "{{ item }}"
    value: "{{ wordpress_db_root_password }}"
    vtype: password
  with_items:
    - root_password
    - root_password_again

- name: Ensure mysql packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server

- name: Start mysql
  service:
    name: mysql
    state: started
